/*
_.each(d20.Campaign.characters.models, function(c) {console.log("{character_name: '"+c.attributes.name+"',");_.each(c.attribs.models, function(a) { console.log(a.attributes.name+":'" +a.attributes.current+"',") });console.log("},")});
*/

var chars = [
    {character_name: 'Chen Yun',
        Mental:'8',
        Physical:'8',
        Social:'8',
        Fight:'8',
        Fly:'12',
        Influence:'12',
        Move:'6',
        Notice:'6',
        Operate:'8',
        Shoot:'10',
        FlySpeciality:'Transport Ships',
        InfluenceSpeciality:'Leadership',
        ShootSpeciality:'Pistols',
        distinction1_name:'Ship’s Captain ',
        distinction1_lore:'Highlighted Skills: Fly, Focus, Influence',
        distinction1_trigger:'Lead the Crew: When one of your crew directly follows one of your orders, spend 1 PP and give that Crewmember an Asset equal to your Influence die rating.',
        distinction1_skill1:'Fly',
        distinction1_skill2:'Focus',
        distinction1_skill3:'Influence',
        distinction1_trigger2:'Protect the Crew: When a Crewmember in the same scene as you acquires a Complication, spend 1 PP to take it away and step it back.',
        distinction1_trigger3:'Lead the Crew: When one of your crew directly follows one of your orders, spend 1 PP and give that Crewmember an Asset equal to your Influence die rating.',
        distinction1_trigger3_enabled:'on',
        distinction2_name:'Mercenary ',
        distinction2_trigger2:'Highest Bidder: Gain 1 PP when you try to get a better deal than your current contract from the side you’re not currently fightin’ for. ',
        distinction2_trigger3:'Time for Some Thrillin’ Heroics: Spend 1 PP to go first in any battle or combat scene. On your first Action, you may reroll any dice that come up 1 instead of accepting a Plot Point.',
        distinction2_lore:'Highlighted Skills: Fight, Move, Shoot',
        distinction2_skill1:'Fight',
        distinction2_skill2:'Move',
        distinction2_skill3:'Shoot',
        distinction3_name:'Ship’s Pilot ',
        distinction3_trigger2:'Born Behind the Wheel: Spend 1 PP to step up or double your ship’s Engines Attribute for your next roll.',
        distinction3_trigger3:'I’ve Never Tried That Before: If you replace your Fly or Operate Skill with a 4 for your next roll, gain a Big Damn Hero Die equal to that Skill’s normal die rating if your roll is successful.',
        distinction3_lore:'Highlighted Skills: Fly, Notice, Operate',
        distinction3_skill1:'Fly',
        distinction3_skill2:'Notice',
        distinction3_skill3:'Operate',
        repeating_sigassets_0_sigasset_name:' Fancy Six-Shooter',
        repeating_sigassets_0_sigasset_value:'8',
        repeating_sigassets_0_sigasset_lore:'  Derelicts floatin’ aimlessly in the black should be easy game, but, on account of the Alliance and rival crews, they’re not. Don’t matter none ’cause your six-shooter never leaves your side. You’re well prepared for trouble wherever it may be.',
        distinction3_trigger2_enabled:'on',
},
{character_name: 'Kit Ketchum',
    short_description: 'A fast talker with a little gambling habit',
    Mental:'8',
    Physical:'6',
    Social:'10',
    Influence:'10',
    Survive:'6',
    InfluenceSpeciality:'Gambling',
    Trick:'10',
    TrickSpeciality:'Slight of Hand',
    Know:'6',
    Notice:'10',
    NoticeSpeciality:'Emotions',
    Fight:'10',
    Focus:'10',
    distinction1_name:'Gambler ',
    distinction2_name:'Reader ',
    distinction3_name:'Sore Loser ',
    distinction1_trigger2:'Risky Business: If you replace your Skill die in a roll with a 4, you get a Big Damn Hero Die equal to that Skill’s normal die rating if you successfully set or raise the stakes.',
    distinction1_trigger2_enabled:'on',
    distinction1_trigger3:'All or Nothing: When you are about to be Taken Out in a scene, spend 1 PP to reroll your dice. If you fail to set or raise the stakes on your second roll, you cannot spend a PP to stay in the fight.',
    distinction1_skill1:'Focus',
    distinction1_skill2:'Notice ',
    distinction1_skill3:'Trick',
    distinction2_trigger2:'Secrets, Secrets: When you are in the presence of someone who is trying to keep a secret, spend 1 PP to discover the secret with a Mental + Know Action. If your Action fails, create or step up a Paranoid Complication.',
    distinction2_trigger3:'Psychic Flashes: Once per scene, spend 1 PP to create a 8 Complication on a Gamemaster character by blurting out a secret or negative fate.',
    distinction2_skill1:'Focus',
    distinction2_skill2:'Influence ',
    distinction2_skill3:'Noticd',
    distinction3_trigger2:'Sulk: Step up a Complication gained in a contest you lost fair and square to gain 1 PP.',
    distinction3_trigger3:'Cheat to Win: Create a 8 Asset of your choice when you openly cheat or lie to win a contest.',
    distinction3_trigger3_enabled:'on',
    distinction3_skill1:'Fight',
    distinction3_skill2:'Know',
    distinction3_skill3:'Focus',
    repeating_sigassets_0_sigasset_trigger:' ',
    repeating_sigassets_0_sigasset_lore:'  You’ve got a terrible habit and deep down inside you know your reputation is spreadin’ in a bad way. To set your mind at ease, you’ve got a collection of fake ident cards that you use to get yourself out of trouble. Though you ain’t sure who you’ll pretend to be next, your ident cards will distract the Law when need be.',
    repeating_sigassets_0_sigasset_value:'8',
    repeating_sigassets_0_sigasset_name:' Fake Ident Cards',
},
{character_name: 'Daniel Thorn Jr., M.D.',
    Know:'8',
    Mental:'10',
    Physical:'6',
    Social:'8',
    Drive:'4',
    Fight:'6',
    Focus:'10',
    Influence:'8',
    KnowSpeciality:'Biology',
    Notice:'6',
    Operate:'10',
    Perform:'6',
    Shoot:'6',
    Treat:'10',
    TreatSpeciality:'Combat Wounds',
    distinction1_name:'First Mate ',
    distinction1_trigger:'',
    distinction2_name:'Ship’s Doctor ',
    distinction3_name:'Drunk ',
    repeating_sigassets_0_sigasset_value:'8',
    repeating_sigassets_0_sigasset_name:' Hip Flask ',
    repeating_sigassets_0_sigasset_lore:'An old, battered hip flask. It’s older than Thorn. It was given to him by his grandfather, on his 18th birthday, and carries a sentimental value, as well as some hard liquor.',
    repeating_sigassets_1_sigasset_name:' Doctor’s Bag',
    repeating_sigassets_1_sigasset_lore:' An old-fashioned leather bag for “doctor stuff”. One of the most prominent contents of the bag is a stethoscope, polished to a shine. Because how can you call yourself a doctor is you don’t have a stethoscope?',
    distinction1_skill1:'Fight',
    distinction1_skill2:'Influence',
    distinction1_skill3:'Notice',
    distinction2_skill1:'Know',
    distinction2_skill2:'Operate',
    distinction2_skill3:'Treat',
    distinction3_skill1:'Influence',
    distinction3_skill2:'Focus',
    distinction3_skill3:'Perform',
    repeating_sigassets_1_0_repeating_sigassets_sigasset_value:'8',
},
{character_name: 'Charles Ankoshka Smith',
    repeating_testshit_0_sigasset_name:'Testhing shisadad',
    repeating_testshit_0_sigasset_value:'6',
    repeating_testshit_1_sigasset_name:'zomg shit balls',
    repeating_testshit_1_sigasset_value:'10',
    repeating_testshit_1_sigasset_mark:'0',
    Mental:'10',
    Physical:'8',
    Social:'6',
    Craft:'10',
    Fix:'10',
    Drive:'8',
    Know:'8',
    Move:'6',
    Notice:'6',
    Operate:'8',
    Shoot:'8',
    Sneak:'6',
    distinction1_name:'Brilliant Gunsmith',
    distinction1_lore:'You’ve got a knack for being a tech wiz. Guns make the most money, so you followed the market.',
    distinction1_trigger:'Gain 1 Plot Point when you roll a d4 instead of a d8.',
    CraftSpeciality:'Firearms',
    KnowSpeciality:'Alliance Armory',
    ShootSpeciality:'Shotguns',
    distinction1_trigger1_enabled:'1',
    distinction2_trigger1_enabled:'1',
    distinction2_trigger2_enabled:'0',
    repeating_sigassets_0_sigasset_trigger1_enabled:'0',
    repeating_sigassets_1_sigasset_value:'8',
},
{character_name: 'Viktor Roux',
    SneakSpeciality:'Infiltrate',
    Fly:'6',
    Social:'6',
    Mental:'10',
    Physical:'8',
    Move:'8',
    Sneak:'12',
    Notice:'6',
    Know:'6',
    KnowSpeciality:'Security Procedures',
    MoveSpeciality:'Climb',
    Operate:'12',
    OperateSpeciality:'Security Systems',
    Perform:'6',
    Shoot:'10',
    distinction1_name:'Invisible Ops',
    distinction1_trigger:'All Access: When you attempt to bypass physical security, double OPERATE for the action.',
    distinction1_trigger2_enabled:'on',
    distinction2_name:'One With the Shadows',
    distinction3_name:'Top Secret',
    repeating_sigassets_0_sigasset_name:' Stealth Suit',
    repeating_sigassets_0_sigasset_value:'8',
    ShootSpeciality:'Precision Shot',
    repeating_sigassets_1_sigasset_name:' Suppressor',
},
{character_name: 'Quentin (Trip) Tuttle III',
    Mental:'10',
    Physical:'8',
    Social:'6',
    Craft:'10',
    Drive:'6',
    Fight:'4',
    Fix:'12',
    Fly:'8',
    Know:'6',
    Move:'6',
    Throw:'10',
    distinction1_name:'Engineer',
    distinction2_name:'Researcher',
    distinction3_name:'Technologist',
}
];
$(function() {
    $(".charsheet").find('*[name^="attr_"]').each(function() {
        var e = $(this);
        var name = e.attr('name').substring(5, e.attr("name").length);
        var type = e.prop('type');
        var sheet_data = chars[1];
        if(!sheet_data[name]) {
            return;
        }
        if( e.get(0).tagName.toLowerCase() == "textarea" ) {
            e.val(sheet_data[name]);
        } else if(type == 'text' || type === undefined) {
            e.attr("value", sheet_data[name]);
        } else if (type === 'checkbox') {
            e.attr("checked", sheet_data[name] == 1 ? 'true' : 'false');
        } else if (type == 'radio') {
            e.prop('checked', e.attr('value') == sheet_data[name]);
        }
    });
});
